#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

rm -fv core

rm -fv \
    precice-*.log \
    precice-postProcessingInfo.log \
    precice-*-events.json \
    *.vtk \
    *.pvd \
    *.vtu
    
rm -rfv \
    cmake_install.cmake \
    CMakeCache.txt \
    Makefile \
    CMakeFiles \
    demo_corrosion

rm -rfv precice-run

echo "Cleaning complete!"
#------------------------------------------------------------------------------
