#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

rm -fv core

rm -fv \
    precice-*.log \
    precice-postProcessingInfo.log \
    precice-*-events.json \
    *.vtk

rm -rfv precice-run

echo "Cleaning complete!"
#------------------------------------------------------------------------------
